Theme = {  }
[Database]
# The type of database to use. Available types: PostgreSql, MySql, SQLite
type = "PostgreSql"
# Address to the database
host = "127.0.0.1"
# Port of the database
port = 5432
# The name of the database
name = "evosc"
# Name of the user to access the database
username = "evosc"
# Password of the user to access the database
password = "evosc"
# A string prefix to add to all table names
tablePrefix = ""

[Logging]
# Possible values lowest to highest verbosity: none, critical, error, warning, information, debug, trace
logLevel = "debug"
# Whether to output logs to the console in JSON.
useJson = false

[Server]
# Address to the Trackmania server
host = "127.0.0.1"
# Port that the XMLRPC is listening to
port = 5000
# Username of the super admin account
username = "SuperAdmin"
# Password of the super admin account
password = "SuperAdmin"
# If enabled, the client will try to reconnect with the server every 1 second until a connection is established
retryConnection = true

[Path]
# Path to the maps folder
maps = ""
# Default match settings file
defaultMatchSettings = "example.txt"

[Modules]
# Signature verification of module's files. If enabled and verification fails, the module will not load.
requireSignatureVerification = true
# Directories to scan for external modules.
moduleDirectories = [ "modules", ]
# Modules that will not load on startup. Note that if a module depend on a disabled module, it will load anyways.
disabledModules = [ ]

[Locale]
# The default display language of the controller. Must be a "language tag" as found here: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c
defaultLanguage = "en"

